name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          # 标签列表（注释需写在标签列表外或用 YAML 注释格式）
          tags: |
            # 标签说明：最新版本
            your-docker-username/cupsd:latest
            # 标签说明：基于 commit SHA 的唯一版本
            your-docker-username/cupsd:${{ github.sha }}
