name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Login to Docker Hub
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: docker/login-action@v3
      with:
       username: muze862
       password: dckr_pat_zN-vJhbd7jaHiTHiLJQ8wIdmFvM
    - name: Push to Docker Hub

        run: 
          docker tag my-image-name:${{ github.sha }} your-username/cupsd:latest
          docker push your-username/cupsd:latest
