# .github/workflows/docker-publish.yml

name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags and labels)
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/mzcupsd
          
          # 已删除 type=ref,event=branch，仅保留语义化标签和SHA标签
          tags: |
            type=semver,pattern={{version}}  # 如 v1.2.3
            type=semver,pattern={{major}}.{{minor}}  # 如 v1.2
            type=semver,pattern={{major}}  # 如 v1
            type=raw,value=build-${{ github.run_number }}-${{ github.run_attempt }}
          # latest 标签逻辑不变
          flavor: |
            latest=true
            onlatest=true

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          labels: ${{ steps.meta.outputs.labels }}
